### ISSUE TITLE
Can wallet configuration support mnemonic besides privatekey?

### ISSUE THREAD

**Issue by geekdadley** [sammchardy/binance-chain-signing-service#1]
'cause certain wallet (bnbcli) only allow backup as mnemonic words.

**Comment by sammchardy** [comment]
No problem. Check out v0.0.3 which allows either private_key or mnemonic when initialising the wallet.

**Comment by geekdadley** [comment]
> No problem. Check out v0.0.3 which allows either private_key or mnemonic when initialising the wallet.

Wow that's a fast one.
